import os

from pyflowline.operation.intersect_flowline_with_mesh_op import intersect_flowline_with_mesh_op
from pyflowline.case.pyflowline_read_model_configuration_file import pyflowline_read_model_configuration_file


sFilename_configuration_in = '/qfs/people/liao313/workspace/python/pyflowline/pyflowline/config/pyflowline_icom_mpas.json'
oPyflowline = pyflowline_read_model_configuration_file(sFilename_configuration_in)


intersect_flowline_with_mesh_op(oPyflowline)

