package:
  name: "pyflowline"
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/changliao1025/pyflowline

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - netCDF4
    - numpy
    - gdal

about:
  home: https://github.com/changliao1025/pyflowline
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Python for River Flowline"

extra:
  recipe-maintainers:
    - changliao1025